#!/usr/bin/env python3
"""contamination_analysis.py — Analyze potential contamination effects.

Compares model accuracy on riddles generated by their own model family
vs. riddles from other families. A significant delta suggests contamination.

For each evaluated model, the script:
1. Loads all eval results from ``results/{version}/*_eval.json``
2. Loads ``data/benchmark.jsonl`` to get the ``source`` field per riddle
3. Determines the model's "family" (e.g. "gemma" from "gemma-4-26b-a4b-it:reasoning")
4. Compares accuracy on self-sourced vs. other-sourced riddles
5. Outputs a formatted table to stdout and saves a report to
   ``results/{version}/contamination_report.json``

Usage:
    python -m scripts.contamination_analysis
    python -m scripts.contamination_analysis --version 2604
    python -m scripts.contamination_analysis --threshold 5.0
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Ensure the repo root is importable when running as a standalone script
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.core.config import (
    DEFAULT_BENCHMARK,
    DEFAULT_RESULTS,
    get_benchmark_version,
)
from scripts.core.io_utils import load_jsonl, write_json

# ── Family extraction ─────────────────────────────────────────────────

# Known family aliases — maps common prefixes/substrings to a canonical
# family name.  Order matters: first match wins.
FAMILY_ALIASES: list[tuple[str, str]] = [
    ("gemma", "gemma"),
    ("gemini", "gemma"),
    ("gpt", "gpt"),
    ("openai", "gpt"),
    ("qwen", "qwen"),
    ("mistral", "mistral"),
    ("glm", "glm"),
    ("zai-org", "glm"),
    ("claude", "claude"),
    ("anthropic", "claude"),
    ("deepseek", "deepseek"),
    ("llama", "llama"),
    ("meta", "llama"),
    ("kimi", "kimi"),
    ("moonshot", "kimi"),
    ("minimax", "minimax"),
    ("abab", "minimax"),
    ("lfm", "lfm"),
    ("liquid", "lfm"),
    ("granite", "granite"),
    ("cohere", "cohere"),
    ("command", "cohere"),
    ("aya", "cohere"),
]


def extract_family(model_name: str) -> str:
    """Extract a canonical family name from a model identifier.

    Examples:
        >>> extract_family("gemma-4-26b-a4b-it:reasoning")
        'gemma'
        >>> extract_family("openai_gpt-oss-120b_reasoning_temp1.0")
        'gpt'
        >>> extract_family("zai-org/glm-5:reasoning")
        'glm'
    """
    lowered = model_name.lower().replace("/", " ").replace("_", " ").replace("-", " ")
    for alias, family in FAMILY_ALIASES:
        if alias in lowered:
            return family
    return model_name.lower().split("/")[-1].split("-")[0].split("_")[0].split(":")[0]


def extract_source_family(source: str) -> str:
    """Extract a canonical family name from a benchmark source field.

    The ``source`` field in benchmark.jsonl uses the generator model name
    (e.g. "gemma-4-31b-it", "zai-org/GLM-5", "mistral-small-2603").
    """
    return extract_family(source)


# ── Data loading ──────────────────────────────────────────────────────


def load_benchmark_sources(benchmark_path: str) -> dict[str, str]:
    """Return a mapping of riddle_id → source family from benchmark.jsonl."""
    entries = load_jsonl(benchmark_path)
    sources: dict[str, str] = {}
    for entry in entries:
        rid = entry.get("id", "")
        source = entry.get("source", "")
        if rid and source:
            sources[rid] = extract_source_family(source)
    return sources


def load_all_eval_results(
    eval_dir: Path,
) -> list[dict]:
    """Load all ``*_eval.json`` files and return a list of eval data dicts."""
    results = []
    for eval_file in sorted(eval_dir.glob("*_eval.json")):
        try:
            with open(eval_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            data["_eval_file"] = eval_file.name
            results.append(data)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"Warning: skipping {eval_file.name}: {exc}", file=sys.stderr)
    return results


# ── Analysis ──────────────────────────────────────────────────────────


def analyze_contamination(
    eval_results: list[dict],
    riddle_sources: dict[str, str],
) -> list[dict]:
    """Compute per-model contamination deltas.

    For each model, compares accuracy on riddles whose source matches the
    model's own family ("self") vs. riddles from other families ("other").

    Returns a list of report entries sorted by absolute delta (descending).
    """
    reports: list[dict] = []

    for eval_data in eval_results:
        model_name = eval_data.get("model", "unknown")
        model_family = extract_family(model_name)

        details = eval_data.get("details", [])
        if not details:
            continue

        # Tally accuracy for self-sourced vs. other-sourced riddles
        self_correct = 0
        self_total = 0
        other_correct = 0
        other_total = 0

        for d in details:
            # Only count altered riddles, first sample
            if d.get("riddle_type") != "altered":
                continue
            if d.get("sample_index", 1) != 1:
                continue

            rid = d.get("riddle_id", "")
            source_family = riddle_sources.get(rid, "")

            if not source_family:
                continue

            is_correct = d.get("correct", False)

            if source_family == model_family:
                self_total += 1
                if is_correct:
                    self_correct += 1
            else:
                other_total += 1
                if is_correct:
                    other_correct += 1

        # Skip models with no self-sourced riddles (can't measure delta)
        if self_total == 0:
            reports.append(
                {
                    "model": model_name,
                    "family": model_family,
                    "self_accuracy": None,
                    "self_correct": 0,
                    "self_total": 0,
                    "other_accuracy": round(other_correct / other_total, 4)
                    if other_total > 0
                    else None,
                    "other_correct": other_correct,
                    "other_total": other_total,
                    "delta": None,
                    "delta_pct": None,
                    "note": "No self-sourced riddles in benchmark",
                }
            )
            continue

        self_acc = self_correct / self_total
        other_acc = other_correct / other_total if other_total > 0 else 0.0
        delta = self_acc - other_acc

        reports.append(
            {
                "model": model_name,
                "family": model_family,
                "self_accuracy": round(self_acc, 4),
                "self_correct": self_correct,
                "self_total": self_total,
                "other_accuracy": round(other_acc, 4),
                "other_correct": other_correct,
                "other_total": other_total,
                "delta": round(delta, 4),
                "delta_pct": round(delta * 100, 2),
                "note": "",
            }
        )

    # Sort by absolute delta descending (most suspicious first), None-deltas last
    reports.sort(key=lambda r: abs(r["delta"]) if r["delta"] is not None else -1, reverse=True)
    return reports


# ── Display ───────────────────────────────────────────────────────────


def print_report_table(reports: list[dict], threshold: float) -> None:
    """Print a formatted table of contamination results to stdout."""
    # Column widths
    col_model = max(len(r["model"]) for r in reports) if reports else 20
    col_model = max(col_model, 5)

    header = (
        f"{'Model':<{col_model}}  "
        f"{'Family':<10}  "
        f"{'Self Acc':>9}  "
        f"{'Self N':>6}  "
        f"{'Other Acc':>9}  "
        f"{'Other N':>7}  "
        f"{'Δ (pp)':>8}  "
        f"{'Flag':>6}"
    )
    sep = "─" * len(header)

    print()
    print("CONTAMINATION ANALYSIS REPORT")
    print(sep)
    print(header)
    print(sep)

    for r in reports:
        self_acc_str = (
            f"{r['self_accuracy'] * 100:.1f}%" if r["self_accuracy"] is not None else "N/A"
        )
        other_acc_str = (
            f"{r['other_accuracy'] * 100:.1f}%" if r["other_accuracy"] is not None else "N/A"
        )

        if r["delta"] is not None:
            delta_str = f"{r['delta_pct']:+.1f}"
            flag = "⚠" if abs(r["delta_pct"]) >= threshold else ""
        else:
            delta_str = "N/A"
            flag = "—"

        note = r.get("note", "")
        if note:
            flag = f"({note[:20]})"

        print(
            f"{r['model']:<{col_model}}  "
            f"{r['family']:<10}  "
            f"{self_acc_str:>9}  "
            f"{r['self_total']:>6}  "
            f"{other_acc_str:>9}  "
            f"{r['other_total']:>7}  "
            f"{delta_str:>8}  "
            f"{flag:>6}"
        )

    print(sep)

    # Summary statistics
    deltas_with_values = [r for r in reports if r["delta"] is not None]
    flagged = [r for r in deltas_with_values if abs(r["delta_pct"]) >= threshold]

    print(f"\nModels analysed:  {len(reports)}")
    print(f"With self-source: {len(deltas_with_values)}")
    print(f"Flagged (|Δ| ≥ {threshold:.0f}pp): {len(flagged)}")

    if deltas_with_values:
        avg_delta = sum(r["delta_pct"] for r in deltas_with_values) / len(deltas_with_values)
        max_delta = max(deltas_with_values, key=lambda r: abs(r["delta_pct"]))
        print(f"Average delta:    {avg_delta:+.2f}pp")
        print(
            f"Largest delta:    {max_delta['delta_pct']:+.1f}pp "
            f"({max_delta['model']}, family={max_delta['family']})"
        )

    if not flagged:
        print("\n✓ No significant contamination signal detected.")
    else:
        print(f"\n⚠ {len(flagged)} model(s) show delta ≥ {threshold:.0f}pp — investigate further.")

    print()


# ── CLI ───────────────────────────────────────────────────────────────


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze potential contamination effects in the benchmark."
    )
    parser.add_argument(
        "--version",
        type=str,
        default=None,
        help="Benchmark version (default: read from data/VERSION)",
    )
    parser.add_argument(
        "--benchmark",
        type=str,
        default=DEFAULT_BENCHMARK,
        help=f"Path to benchmark.jsonl (default: {DEFAULT_BENCHMARK})",
    )
    parser.add_argument(
        "--results-dir",
        type=str,
        default=DEFAULT_RESULTS,
        help=f"Base results directory (default: {DEFAULT_RESULTS})",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=5.0,
        help="Flag models with |delta| >= this value in percentage points (default: 5.0)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Custom output path for the JSON report",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    version = args.version or get_benchmark_version()
    eval_dir = Path(args.results_dir) / version

    if not eval_dir.exists():
        print(f"Error: eval directory not found: {eval_dir}", file=sys.stderr)
        return 1

    # Load data
    print(f"Loading benchmark metadata from {args.benchmark} ...")
    riddle_sources = load_benchmark_sources(args.benchmark)
    if not riddle_sources:
        print("Error: no riddle sources found in benchmark.jsonl", file=sys.stderr)
        return 1

    source_families = set(riddle_sources.values())
    print(
        f"  Found {len(riddle_sources)} riddles from {len(source_families)} families: "
        f"{', '.join(sorted(source_families))}"
    )

    print(f"Loading eval results from {eval_dir} ...")
    eval_results = load_all_eval_results(eval_dir)
    if not eval_results:
        print("Error: no eval files found", file=sys.stderr)
        return 1
    print(f"  Loaded {len(eval_results)} eval file(s)")

    # Analyse
    reports = analyze_contamination(eval_results, riddle_sources)

    # Display
    print_report_table(reports, threshold=args.threshold)

    # Save JSON report
    output_path = args.output or str(eval_dir / "contamination_report.json")
    report_data = {
        "version": version,
        "threshold_pp": args.threshold,
        "source_families": sorted(source_families),
        "num_riddles": len(riddle_sources),
        "num_models": len(reports),
        "models": reports,
    }

    write_json(output_path, report_data)
    print(f"Report saved: {output_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
